### ISSUE TITLE
There's no way to get/change password of generated free sandbox salesforce account

### ISSUE THREAD

**Issue by Vergil333** [NetAppDocs/salesforce#22]
The issue is related to [this](https://github.com/NetAppDocs/salesforce/blob/main/task_signing_up_free_sandbox_account.adoc) or [this](https://docs.netapp.com/us-en/salesforce/task_signing_up_free_sandbox.html) process.

**Step 3 is invalid** - the email I get does not provide a link to create a password. Instead I receive 2 emails informing me about automatic installation of 2 packages ("volunteeringBasePkg volunteering core" and "recruitingPkg v 1.0").

I can get into created sandbox account though. I'm redirected there when the creation process is finished (from step 1).
I can check the generated username. I can even click on "change password" but I can't change it because I don't know the **old password**.

**Comment by Vergil333** [comment]
Creating the sandbox account via https://developer.salesforce.com/signup worked. I received the email with verification link where I had to set the password and security question.

**Comment by netapp-rlithman** [comment]
Hi Martin. Thanks for reaching out to us about this issue. I see you closed the issue. I want to follow up in case the user documentation needs revision. Is any action required?

**Comment by Vergil333** [comment]
Hi Rachel, actually the issue still persists as described. I just closed the issue, because I solved "mine issue" by creating sandbox account different way then in NetApp tutorial.

When I need another testing account, I can have another look at your tutorial steps and update them.
