### ISSUE TITLE
Getting Started link is broken

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/salesforce#9]
Page: [NetApp SaaS Backup for Salesforce documentation](https://docs.netapp.com/us-en/salesforce/index.html)

**Comment by netapp-rlithman** [comment]
Hi Phoebe, 
Thanks for letting us know about the broken link. I have updated the documentation to repair the link and reflect the two new links for [Getting Started](https://docs.netapp.com/us-en/salesforce/index.html).
